### ISSUE TITLE
stoped working

### ISSUE THREAD

**Issue by lcostaracing7** [vinsce/firefox-ig-autolike#2]
After the firefox developer update when i start running the autolike it starts, likes 1 pic and stops

**Comment by vinsce** [comment]
> After the firefox developer update when i start running the autolike it starts, likes 1 pic and stops

Hi @lcostaracing7 , Instagram changed something. I just updated the extension. [Check  it](https://github.com/vinsce/firefox-ig-autolike/blob/master/web-ext-artifacts/ig_autolike-0.1.9.2.xpi).

**Comment by lcostaracing7** [comment]
> 
> 
> After the firefox developer update when i start running the autolike it starts, likes 1 pic and stops

same thing is happening again btw thank you very much for this

**Comment by vinsce** [comment]
> same thing is happening again btw thank you very much for creating this @vinsce

Fixed again, thank you for reporting
